### ISSUE TITLE
make tags work in circleCI

### ISSUE THREAD

**Issue by carolineolivia** [prolike/web-lab#8]

**Comment by lakruzz** [comment]
@carolineolivia 

[The problem in the workflow that it _also_ builds on master](https://github.com/prolike/web-lab/blob/dc556fde4e653863f427e02913cdd3af6574112c/.circleci/config.yml#L119)

Is related to the fact (YOU WERE RIGHT) that is _should_ ignore all branches! as in it should only be triggered by tags!


[![image](https://user-images.githubusercontent.com/155492/52368309-60b80880-2a4e-11e9-9856-15b1c77c3add.png)](https://circleci.com/docs/2.0/workflows/)
